#!/usr/bin/env bash

SRCDIR=/glade/work/jkshuman/git/ctsm/src/fates

FILEWRK=/glade/work/jkshuman/FATES_data/parameter_files

### Obrien.h Salda.a, Salda.l grass agb1=0.001, latosa_int = default (strict PPA)
SETUP_CASE=2PFT_TreeC3Gr_Obrienh_Saldaa_Saldal_181219

cd /glade/work/jkshuman/jkshuman_python_20181024/bin
source activate
pip install pyparsing

### generate a fates parameter file for this experiment.  this requires loading some modules to allow manipulation of the netcdf parameter files
module load matplotlib
module load scipy
ncgen -o $FILEWRK/param_file_${SETUP_CASE}.nc $SRCDIR/parameter_files/fates_params_default.cdl

### now modify the default 2 PFT parameter file
### update all pfts for params of interest, pfts now indexed as 1,2 to be 1: moist trop tree, 2: C3 grass

### set to strict PPA with comp excln = -1
$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_comp_excln --val -1

### set initd for PFT 2 grass
$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_recruit_initd --val 0.2 --PFT 2


#allometric
$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_allom_agb1 --val 0.0001 --PFT 2

$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_allom_dbh_maxheight --val 80 --PFT 1
$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_allom_dbh_maxheight --val 0.3744 --PFT 2

#branch
$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_branch_turnover --val 25 --allpfts

#fire
$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_fire_alpha_SH --val 0.1487 --PFT 1
$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_fire_bark_scaler --val 0.077 --PFT 1

#leaf
$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_leaf_long --val 1.4025 --PFT 1
$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_leaf_long --val 0.3208 --PFT 2

$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_leaf_slatop --val 0.01892 --PFT 1
$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_leaf_slamax --val 0.04024 --PFT 2
#set slamax to = slatop to turn off changes by M. Kovenock
$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_leaf_slamax --val 0.01892 --PFT 1
$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_leaf_slamax --val 0.04024 --PFT 2

$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_leaf_vcmax25top --val 61 --PFT 1
$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_leaf_vcmax25top --val 78 --PFT 2

#phenology
$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_phen_evergreen --val 1 --allpfts
$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_phen_season_decid --val 0 --allpfts
$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_phen_stress_decid --val 0 --allpfts

#recruit
$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_recruit_hgt_min --val 0.125 --PFT 2

#visible
$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_rholnir --val 0.45 --PFT 1
$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_rholnir --val 0.35 --PFT 2

$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_rhosnir --val 0.39 --PFT 1
$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_rhosnir --val 0.53 --PFT 2

$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_rhosvis --val 0.16 --PFT 1
$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_rhosvis --val 0.31 --PFT 2

#root
$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_roota_par --val 7 --PFT 1
$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_roota_par --val 11 --PFT 2

$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_rootb_par --val 1 --PFT 1
$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_rootb_par --val 2 --PFT 2

#seed
$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_seed_alloc_mature --val 0.9 --PFT 2
$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_seed_dbh_repro_threshold --val 6.807 --PFT 1
$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_seed_dbh_repro_threshold --val 0.3744 --PFT 2

#woody=1
$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_woody --val 1 --PFT 1
$SRCDIR/tools/modify_fates_paramfile.py --fin $FILEWRK/param_file_${SETUP_CASE}.nc --fout $FILEWRK/param_file_${SETUP_CASE}.nc --O --var fates_woody --val 0 --PFT 2


### unload the modules needed to manipulate the netcdf file
module unload matplotlib
module unload scipy

